name: Sync labels
on:
  workflow_dispatch:

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-20.04
    permissions:
        contents: write
        pull-requests: write
        repository-projects: writ
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: 'https://raw.githubusercontent.com/John-Drake/pyOpenSci_fix_labels/main/labels.yml'